version: "2"
services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

  pubsub-service:
    build:
      context: ./pubsubkafka
      dockerfile: Dockerfile
    container_name: pubsub-service
    networks:
      - kafkanet
    ports:
       - "1008:1008"
    links:
      - eureka-service
      - kafkaserver
    depends_on:
      - eureka-service
      - kafkaserver
    environment:
        KAFKA_BOOTSTRAP-SERVERS: "kafkaserver:2181,kafkaserver:9092"
        KAFKA_TOPIC_TEST: "kafka_test_topic"
        SPRING_APPLICATION_NAME: pubsub-service
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
  eureka-service:
    build:
      context: ./eureakaserver
      dockerfile: Dockerfile
    container_name: eureka-service
    networks:
      - kafkanet
    ports:
      - "8761:8761"
    environment:
        SPRING_APPLICATION_NAME: eureka-service
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/

  rest-service:
    build:
      context: ./restservice
      dockerfile: Dockerfile
    container_name: rest-service
    networks:
      - kafkanet
    ports:
       - "8083:8083"
    links:
       - eureka-service
    depends_on:
      - eureka-service
    environment:
        SPRING_APPLICATION_NAME: rest-service
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/

  zuul-service:
    build:
      context: ./ZuulGateway
      dockerfile: Dockerfile
    networks:
      - kafkanet
    ports:
      - "9091:9091"
    links:
      - eureka-service
      - rest-service
    depends_on:
      - eureka-service
      - rest-service
    environment:
        SPRING_APPLICATION_NAME: zuul-service
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
        ZUUL_ROUTES_REST_URL: http://rest-service:8083

networks:
  kafkanet:
    driver: bridge