server:
  port: 8083
spring:
  application:
    name: REST-APP

eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true
    healthcheck:
       enabled: true